language: php
php: [7.0, 7.1, 7.2, nightly ]
sudo: false

env:
  global:
    - VERSION=$(echo $TRAVIS_TAG | cut -c 2-10)

install:
- composer install --no-interaction --prefer-dist -o

jobs:
  include:
    - stage: Test
      script:
        - bin/phpunit --no-coverage
        - bin/behat

    - stage: Lint
      php: 7.1
      script: ./tools/phpstan analyse src tests --level 2 --configuration phpstan.neon
      before_script:
        - wget https://phar.io/releases/phive.phar
        - wget https://phar.io/releases/phive.phar.asc
        - gpg --keyserver hkps.pool.sks-keyservers.net --recv-keys 0x9B2D5D79
        - gpg --verify phive.phar.asc phive.phar
        - php phive.phar install --trust-gpg-keys 8E730BA25823D8B5

    - stage: Coverage
      php: 7.1
      script:
        - bin/phpunit
      after_script:
        - wget https://scrutinizer-ci.com/ocular.phar
        - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml

    - stage: Release
      php: 7.1
      script:
        - echo "${VERSION}" > VERSION
        - php -d phar.readonly=false box.phar build
        - openssl sha1 phpDocumentor.phar
        - echo "Update https://github.com/josegonzalez/homebrew-php/blob/master/Formula/phpdocumentor.rb with the latest version number and the SHA1 that is shown above with the path /get/phpDocumentor-${VERSION}.phar"
      deploy:
        provider: releases
        api_key:
          secure: WUchZXQQdIDtVQTYZsQ++2R1y6I+EzBrAACRuc33wAVd0mlqNmu3nb/c1Ou4pTk5JxjyGqm9Siyp9vobhBtzBh/hdXAnbZDWNx2l6R1M9S4R/Z/VbcQ+uIJ/VOoh2KvIOCcyVuFVmsemlVQCuatCRKswKmK/OuyQXy6ppyZMilA=
        file: "phpDocumentor.phar"
        skip_cleanup: true
        on:
          repo: phpDocumentor/phpDocumentor2
          tags: true

  allow_failures:
    - php: nightly


cache:
  directories:
  - $HOME/.composer/cache/files

notifications:
  irc: irc.freenode.org#phpdocumentor
  slack:
    secure: fjumM0h+4w3EYM4dpgqvpiCug7m4sSIC5+HATgwga/Nrc6IjlbWvGOv3JPgD3kQUhi18VmZfUYPmCv916SIbMnv8JWcrSaJXnPCgmxidvYkuzQDIw1HDJbVppGnkmwQA/qjIrM3sIEMfnu/arLRJQLI363aStZzGPxwIa4PDKcg=
  email:
  - me@mikevanriel.com
  - ashnazg@php.net
