language: php
php:
  - 7.1
  - 7.2
  - nightly
sudo: false

env:
matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

install:
  - composer install --no-interaction --prefer-dist --optimize-autoloader

jobs:
  include:
    - stage: test
      script:
      - bin/phpunit --no-coverage
      - bin/behat

    - stage: coverage
      php: 7.1
      script:
        - bin/phpunit
      after_script:
        - wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml
        - wget https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar && php coveralls.phar --verbose

    - stage: lint
      php: 7.1
      services:
        - docker
      script:
        - docker-compose run --rm esc
        - docker-compose run --rm phpstan

    - stage: release
      if: type IN (push)
      php: 7.1
      env:
        - VERSION=$(echo $TRAVIS_TAG | cut -c 2-10)
      script:
        - echo "${VERSION}" > VERSION
        - php -d phar.readonly=false box.phar build
        - openssl sha1 phpDocumentor.phar
        - echo "Update https://github.com/josegonzalez/homebrew-php/blob/master/Formula/phpdocumentor.rb with the latest version number and the SHA1 that is shown above with the path /get/phpDocumentor-${VERSION}.phar"
      deploy:
        provider: releases
        api_key:
          secure: WUchZXQQdIDtVQTYZsQ++2R1y6I+EzBrAACRuc33wAVd0mlqNmu3nb/c1Ou4pTk5JxjyGqm9Siyp9vobhBtzBh/hdXAnbZDWNx2l6R1M9S4R/Z/VbcQ+uIJ/VOoh2KvIOCcyVuFVmsemlVQCuatCRKswKmK/OuyQXy6ppyZMilA=
        file: "phpDocumentor.phar"
        skip_cleanup: true
        on:
          repo: phpDocumentor/phpDocumentor2
          tags: true

cache:
  directories:
  - $HOME/.composer/cache/files

notifications:
  irc: "irc.freenode.org#phpdocumentor"
  slack:
    secure: "fjumM0h+4w3EYM4dpgqvpiCug7m4sSIC5+HATgwga/Nrc6IjlbWvGOv3JPgD3kQUhi18VmZfUYPmCv916SIbMnv8JWcrSaJXnPCgmxidvYkuzQDIw1HDJbVppGnkmwQA/qjIrM3sIEMfnu/arLRJQLI363aStZzGPxwIa4PDKcg="
  email:
  - me@mikevanriel.com
  - ashnazg@php.net
