language: php
php:
  - 5.3.3
  - 5.3
  - 5.4
  - 5.5
  - 5.6

script:
 - bin/phpunit
 - bin/behat --no-paths --format failed

before_script:
 - sudo apt-get -qq update > /dev/null
 - sudo apt-get -qq install graphviz > /dev/null
 - phpenv rehash > /dev/null
 - composer selfupdate --quiet
 - composer install -n --prefer-source --dev
 - bin/phpunit
 - bin/behat --no-paths --format failed
 - composer update -n --prefer-source --dev

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml

notifications:
  irc: "irc.freenode.org#phpdocumentor"
  email:
    - me@mikevanriel.com
    - ashnazg@php.net

matrix:
  allow_failures:
    - hhvm
