build: false
clone_folder: c:\phpdocumentor
max_jobs: 3
platform: x86
pull_requests:
  do_not_increment_build_number: true
version: '{build}.{branch}'
skip_tags: true
branches:
  only:
    - master
    - develop

environment:
  matrix:
    - PHP_VERSION: '5.4.45'
      VC_VERSION: 'VC9'
      BEHAT_FLAGS: '--suite=core_features'
    - PHP_VERSION: '5.5.37'
      VC_VERSION: 'VC11'
      BEHAT_FLAGS: '--suite=core_features'
    - PHP_VERSION: '5.6.29'
      VC_VERSION: 'VC11'
    - PHP_VERSION: '7.0.18'
      VC_VERSION: 'VC14'
    - PHP_VERSION: '7.1.4'
      VC_VERSION: 'VC14'
matrix:
  fast_finish: false

cache:
  - c:\php -> appveyor.yml
  - '%LOCALAPPDATA%\Composer\files'

init:
  - SET PATH=c:\php\%PHP_VERSION%;%PATH%

install:
  - IF NOT EXIST c:\php mkdir c:\php
  - IF NOT EXIST c:\php\%PHP_VERSION% mkdir c:\php\%PHP_VERSION%
  - cd c:\php\%PHP_VERSION%
  - IF NOT EXIST php-installed.txt appveyor DownloadFile http://windows.php.net/downloads/releases/archives/php-%PHP_VERSION%-Win32-%VC_VERSION%-x86.zip
  - IF NOT EXIST php-installed.txt 7z x php-%PHP_VERSION%-Win32-%VC_VERSION%-x86.zip -y >nul
  - IF NOT EXIST php-installed.txt del /Q *.zip
  - IF NOT EXIST php-installed.txt copy /Y php.ini-development php.ini
  - IF NOT EXIST php-installed.txt echo max_execution_time=1200 >> php.ini
  - IF NOT EXIST php-installed.txt echo date.timezone="UTC" >> php.ini
  - IF NOT EXIST php-installed.txt echo extension_dir=ext >> php.ini
  - IF NOT EXIST php-installed.txt echo extension=php_curl.dll >> php.ini
  - IF NOT EXIST php-installed.txt echo extension=php_openssl.dll >> php.ini
  - IF NOT EXIST php-installed.txt echo extension=php_mbstring.dll >> php.ini
  - IF NOT EXIST php-installed.txt echo extension=php_fileinfo.dll >> php.ini
  - IF NOT EXIST php-installed.txt echo zend.assertions=1 >> php.ini
  - IF NOT EXIST php-installed.txt echo assert.exception=On >> php.ini
  - IF NOT EXIST php-installed.txt appveyor DownloadFile https://getcomposer.org/composer.phar
  - IF NOT EXIST php-installed.txt echo @php %%~dp0composer.phar %%* > composer.bat
  - IF NOT EXIST php-installed.txt type nul >> php-installed.txt
  - cd c:\phpdocumentor
  - composer install --no-interaction --prefer-dist --no-progress

test_script:
  - cd c:\phpdocumentor
  - bin/phpunit
  - bin/behat %BEHAT_FLAGS%
