services:
  console_formatter:
    class: Monolog\Formatter\LineFormatter
    arguments:
      - "[%%datetime%%]: %%message%%\n"
      - 'H:i:s'

monolog:
    handlers:
        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: ["!event"]
        console:
            type:   console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine", "!console"]
            verbosity_levels:
                VERBOSITY_NORMAL: NOTICE
                VERBOSITY_VERBOSE: INFO
                VERBOSITY_VERY_VERBOSE: DEBUG
            formatter: console_formatter
