on: [push]
name: Docs & Demo
jobs:
#  docs:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@master
#      - name: Build
#        uses: elgohr/Publish-Docker-Github-Action@master
#        with:
#          name: phpdocumentor/phpdocumentor/docs.phpdoc.org
#          username: ${{ github.actor }}
#          password: ${{ secrets.GITHUB_TOKEN }}
#          registry: docker.pkg.github.com
#          context: docs
  demo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: ./ # use this repo as an action
        with:
          template: 'clean'
          config: 'data/examples/MariosPizzeria/phpdoc.xml'
          target: 'build/clean'
