on: [issues]
name: Issue Triage
jobs:
  add-new-issues-to-project-column:
    runs-on: ubuntu-latest
    steps:
      - name: add-new-issues-to-organization-based-project-column
        uses: docker://takanabe/github-actions-automate-projects:v0.0.1
        if: github.event_name == 'issues' && github.event.action == 'opened'
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
          GITHUB_PROJECT_URL: https://github.com/orgs/phpDocumentor/projects/4
          GITHUB_PROJECT_COLUMN_NAME: Needs triage
